const workflow ={
    Created:{
    next:["Assigned"],
    actor:["system"]
    },
    Assigned:{
        next:["WorkerAccepted"],
        actor:["worker"]
    },
    WorkerAccepted:{
        next:["Checking"],
        actor:["worker"]
    },
    Checking:{
        next:["Reject","EstimateSubmitted"],
        actor:["worker"]
    },
    EstimateSubmitted:{
        next:["WaitingCustomerApproval","TemporaryFixApproved","Reject"],
        actor:["worker"]
    },
    WaitingCustomerApproval:{
        next:["InProgress"],
        actor:["customer"]
    },
    TemporaryFixApproved:{
        next:["InProgress"],
        actor:["customer"]
    },
    Reject:{
        next:[],
        actor:["customer","worker","admin","system"]
    },
    InProgress:{
        next:["WorkCompleted"],
        actor:['worker']
    },
    WorkCompleted:{
        next:["VerificationPending"],
        actor:["worker"]
    },
    VerificationPending:{
        next:["Verified","ReworkRequired"],
        actor:["customer"]
    },
    ReworkRequired:{
        next:["InProgress"],
        actor:["customer"]  
    },
    Verified:{
        next:[],
        actor:["customer"]
    }
}
module.exports = workflow;